var TREE_DATA = {"name":"kart-racer-report-public","type":"dir","path":"","children":[
{"name":"1335_game_12472357.jsonl","type":"file","path":"1335_game_12472357.jsonl"}
,
{"name":"1337_kart-gen_fdd76289.jsonl","type":"file","path":"1337_kart-gen_fdd76289.jsonl"}
,
{"name":"1346_kart-gen_05083f38.jsonl","type":"file","path":"1346_kart-gen_05083f38.jsonl"}
,
{"name":"1507_game_5b20ba3e.jsonl","type":"file","path":"1507_game_5b20ba3e.jsonl"}
,
{"name":"1514_kart_b560804e.jsonl","type":"file","path":"1514_kart_b560804e.jsonl"}
,
{"name":"1525_kart_a1de3ed5.jsonl","type":"file","path":"1525_kart_a1de3ed5.jsonl"}
,
{"name":"1530_kart_a6bc1367.jsonl","type":"file","path":"1530_kart_a6bc1367.jsonl"}
,
{"name":"1644_kart_68c0a196.jsonl","type":"file","path":"1644_kart_68c0a196.jsonl"}
,
{"name":"1832_kart_d21b341c.jsonl","type":"file","path":"1832_kart_d21b341c.jsonl"}
,
{"name":"1850_kart_94ab251a.jsonl","type":"file","path":"1850_kart_94ab251a.jsonl"}
,
{"name":"1908_kart3deditor_008d06a2.jsonl","type":"file","path":"1908_kart3deditor_008d06a2.jsonl"}
,
{"name":"1958_kart_cc79f42b.jsonl","type":"file","path":"1958_kart_cc79f42b.jsonl"}
,
{"name":"2035_kart_d83ae248.jsonl","type":"file","path":"2035_kart_d83ae248.jsonl"}
,
{"name":"2051_kart_37a26c13.jsonl","type":"file","path":"2051_kart_37a26c13.jsonl"}
,
{"name":"2131_kart_29c70273.jsonl","type":"file","path":"2131_kart_29c70273.jsonl"}
,
{"name":"2229_kart_c86150f1.jsonl","type":"file","path":"2229_kart_c86150f1.jsonl"}
,
{"name":"2230_game2_24442944.jsonl","type":"file","path":"2230_game2_24442944.jsonl"}
,
{"name":"2232_kart_44e99b1b.jsonl","type":"file","path":"2232_kart_44e99b1b.jsonl"}
,
{"name":"2234_kart_b2a9b3a5.jsonl","type":"file","path":"2234_kart_b2a9b3a5.jsonl"}
,
{"name":"2324_kart_9e6cfa69.jsonl","type":"file","path":"2324_kart_9e6cfa69.jsonl"}
,
{"name":"2333_kart_389c6774.jsonl","type":"file","path":"2333_kart_389c6774.jsonl"}
,
{"name":"debug-graph.png","type":"file","path":"debug-graph.png"}
,
{"name":"index.html","type":"file","path":"index.html"}
,
{"name":"report","type":"dir","path":"report","children":[
{"name":"app.js","type":"file","path":"report/app.js"}
,
{"name":"build.sh","type":"file","path":"report/build.sh"}
,
{"name":"chat-data.js","type":"file","path":"report/chat-data.js"}
,
{"name":"style.css","type":"file","path":"report/style.css"}
,
{"name":"tree-data.js","type":"file","path":"report/tree-data.js"}
]}
,
{"name":"screenshot-driving-01.png","type":"file","path":"screenshot-driving-01.png"}
,
{"name":"screenshot-driving-hills.png","type":"file","path":"screenshot-driving-hills.png"}
,
{"name":"screenshot-gamepad.png","type":"file","path":"screenshot-gamepad.png"}
,
{"name":"screenshot-itemboxes.png","type":"file","path":"screenshot-itemboxes.png"}
,
{"name":"screenshot-kartgen.png","type":"file","path":"screenshot-kartgen.png"}
,
{"name":"screenshot-levelselect.png","type":"file","path":"screenshot-levelselect.png"}
,
{"name":"screenshot-mapeditor.png","type":"file","path":"screenshot-mapeditor.png"}
,
{"name":"screenshot-race-4th.png","type":"file","path":"screenshot-race-4th.png"}
,
{"name":"screenshot-race-start.png","type":"file","path":"screenshot-race-start.png"}
,
{"name":"screenshot-skidmarks.png","type":"file","path":"screenshot-skidmarks.png"}
,
{"name":"snapshots","type":"dir","path":"snapshots","children":[
{"name":"01-1500-engine-and-sprites","type":"dir","path":"snapshots/01-1500-engine-and-sprites","children":[
{"name":"game","type":"dir","path":"snapshots/01-1500-engine-and-sprites/game","children":[
{"name":"index.html","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/index.html"}
,
{"name":"src","type":"dir","path":"snapshots/01-1500-engine-and-sprites/game/src","children":[
{"name":"camera.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/camera.js"}
,
{"name":"debug.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/debug.js"}
,
{"name":"input.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/input.js"}
,
{"name":"kart.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/kart.js"}
,
{"name":"main.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/main.js"}
,
{"name":"map-loader.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/map-loader.js"}
,
{"name":"menu.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/menu.js"}
,
{"name":"physics.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/physics.js"}
,
{"name":"track.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/src/track.js"}
]}
,
{"name":"vite.config.js","type":"file","path":"snapshots/01-1500-engine-and-sprites/game/vite.config.js"}
]}
,
{"name":"kart-gen","type":"dir","path":"snapshots/01-1500-engine-and-sprites/kart-gen","children":[
{"name":"index.html","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src","children":[
{"name":"main.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/main.ts"}
,
{"name":"objects","type":"dir","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/objects","children":[
{"name":"example-cart.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/objects/example-cart.ts"}
,
{"name":"firetruck.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/objects/firetruck.ts"}
,
{"name":"registry.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/objects/registry.ts"}
,
{"name":"types.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/objects/types.ts"}
,
{"name":"wonky-kart.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/objects/wonky-kart.ts"}
]}
,
{"name":"renderer.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/renderer.ts"}
,
{"name":"sprite-exporter.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/sprite-exporter.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/kart-gen/vite.config.ts"}
]}
,
{"name":"map-editor","type":"dir","path":"snapshots/01-1500-engine-and-sprites/map-editor","children":[
{"name":"index.html","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/01-1500-engine-and-sprites/map-editor/src","children":[
{"name":"editor.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/src/editor.ts"}
,
{"name":"main.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/src/main.ts"}
,
{"name":"save.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/src/save.ts"}
,
{"name":"state.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/src/state.ts"}
,
{"name":"tools.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/src/tools.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/01-1500-engine-and-sprites/map-editor/vite.config.ts"}
]}
]}
,
{"name":"02-1640-maps-and-editor","type":"dir","path":"snapshots/02-1640-maps-and-editor","children":[
{"name":"game","type":"dir","path":"snapshots/02-1640-maps-and-editor/game","children":[
{"name":"index.html","type":"file","path":"snapshots/02-1640-maps-and-editor/game/index.html"}
,
{"name":"src","type":"dir","path":"snapshots/02-1640-maps-and-editor/game/src","children":[
{"name":"camera.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/camera.js"}
,
{"name":"debug.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/debug.js"}
,
{"name":"input.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/input.js"}
,
{"name":"kart.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/kart.js"}
,
{"name":"main.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/main.js"}
,
{"name":"map-loader.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/map-loader.js"}
,
{"name":"menu.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/menu.js"}
,
{"name":"physics.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/physics.js"}
,
{"name":"track.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/src/track.js"}
]}
,
{"name":"vite.config.js","type":"file","path":"snapshots/02-1640-maps-and-editor/game/vite.config.js"}
]}
,
{"name":"gamepad-test","type":"dir","path":"snapshots/02-1640-maps-and-editor/gamepad-test","children":[
{"name":"index.html","type":"file","path":"snapshots/02-1640-maps-and-editor/gamepad-test/index.html"}
,
{"name":"main.js","type":"file","path":"snapshots/02-1640-maps-and-editor/gamepad-test/main.js"}
]}
,
{"name":"kart-gen","type":"dir","path":"snapshots/02-1640-maps-and-editor/kart-gen","children":[
{"name":"index.html","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/02-1640-maps-and-editor/kart-gen/src","children":[
{"name":"main.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/main.ts"}
,
{"name":"objects","type":"dir","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/objects","children":[
{"name":"example-cart.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/objects/example-cart.ts"}
,
{"name":"firetruck.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/objects/firetruck.ts"}
,
{"name":"registry.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/objects/registry.ts"}
,
{"name":"types.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/objects/types.ts"}
,
{"name":"wonky-kart.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/objects/wonky-kart.ts"}
]}
,
{"name":"renderer.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/renderer.ts"}
,
{"name":"sprite-exporter.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/sprite-exporter.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/kart-gen/vite.config.ts"}
]}
,
{"name":"map-editor","type":"dir","path":"snapshots/02-1640-maps-and-editor/map-editor","children":[
{"name":"index.html","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/02-1640-maps-and-editor/map-editor/src","children":[
{"name":"editor.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/src/editor.ts"}
,
{"name":"main.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/src/main.ts"}
,
{"name":"save.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/src/save.ts"}
,
{"name":"state.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/src/state.ts"}
,
{"name":"tools.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/src/tools.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/02-1640-maps-and-editor/map-editor/vite.config.ts"}
]}
]}
,
{"name":"03-1900-race-and-bots","type":"dir","path":"snapshots/03-1900-race-and-bots","children":[
{"name":"game","type":"dir","path":"snapshots/03-1900-race-and-bots/game","children":[
{"name":"index.html","type":"file","path":"snapshots/03-1900-race-and-bots/game/index.html"}
,
{"name":"src","type":"dir","path":"snapshots/03-1900-race-and-bots/game/src","children":[
{"name":"boost-pad.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/boost-pad.js"}
,
{"name":"bot-input.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/bot-input.js"}
,
{"name":"camera.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/camera.js"}
,
{"name":"debug.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/debug.js"}
,
{"name":"ground-decal.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/ground-decal.js"}
,
{"name":"hud.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/hud.js"}
,
{"name":"input.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/input.js"}
,
{"name":"kart-collision.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/kart-collision.js"}
,
{"name":"kart.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/kart.js"}
,
{"name":"main.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/main.js"}
,
{"name":"map-loader.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/map-loader.js"}
,
{"name":"menu.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/menu.js"}
,
{"name":"physics.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/physics.js"}
,
{"name":"race.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/race.js"}
,
{"name":"start-line.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/start-line.js"}
,
{"name":"track.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/src/track.js"}
]}
,
{"name":"vite.config.js","type":"file","path":"snapshots/03-1900-race-and-bots/game/vite.config.js"}
]}
,
{"name":"gamepad-test","type":"dir","path":"snapshots/03-1900-race-and-bots/gamepad-test","children":[
{"name":"index.html","type":"file","path":"snapshots/03-1900-race-and-bots/gamepad-test/index.html"}
,
{"name":"main.js","type":"file","path":"snapshots/03-1900-race-and-bots/gamepad-test/main.js"}
]}
,
{"name":"kart-gen","type":"dir","path":"snapshots/03-1900-race-and-bots/kart-gen","children":[
{"name":"index.html","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/03-1900-race-and-bots/kart-gen/src","children":[
{"name":"main.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/main.ts"}
,
{"name":"objects","type":"dir","path":"snapshots/03-1900-race-and-bots/kart-gen/src/objects","children":[
{"name":"example-cart.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/objects/example-cart.ts"}
,
{"name":"firetruck.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/objects/firetruck.ts"}
,
{"name":"registry.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/objects/registry.ts"}
,
{"name":"types.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/objects/types.ts"}
,
{"name":"wonky-kart.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/objects/wonky-kart.ts"}
]}
,
{"name":"renderer.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/renderer.ts"}
,
{"name":"sprite-exporter.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/sprite-exporter.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/03-1900-race-and-bots/kart-gen/vite.config.ts"}
]}
,
{"name":"map-editor","type":"dir","path":"snapshots/03-1900-race-and-bots/map-editor","children":[
{"name":"index.html","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/03-1900-race-and-bots/map-editor/src","children":[
{"name":"editor.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/src/editor.ts"}
,
{"name":"main.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/src/main.ts"}
,
{"name":"save.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/src/save.ts"}
,
{"name":"state.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/src/state.ts"}
,
{"name":"tools.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/src/tools.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/03-1900-race-and-bots/map-editor/vite.config.ts"}
]}
]}
,
{"name":"04-2130-items-and-effects","type":"dir","path":"snapshots/04-2130-items-and-effects","children":[
{"name":"game","type":"dir","path":"snapshots/04-2130-items-and-effects/game","children":[
{"name":"index.html","type":"file","path":"snapshots/04-2130-items-and-effects/game/index.html"}
,
{"name":"src","type":"dir","path":"snapshots/04-2130-items-and-effects/game/src","children":[
{"name":"boost-pad.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/boost-pad.js"}
,
{"name":"boost-visual.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/boost-visual.js"}
,
{"name":"bot-input.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/bot-input.js"}
,
{"name":"camera.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/camera.js"}
,
{"name":"debug.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/debug.js"}
,
{"name":"ground-decal.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/ground-decal.js"}
,
{"name":"hud.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/hud.js"}
,
{"name":"input.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/input.js"}
,
{"name":"item-boxes.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/item-boxes.js"}
,
{"name":"kart-collision.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/kart-collision.js"}
,
{"name":"kart.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/kart.js"}
,
{"name":"kart-visuals.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/kart-visuals.js"}
,
{"name":"main.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/main.js"}
,
{"name":"map-loader.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/map-loader.js"}
,
{"name":"menu.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/menu.js"}
,
{"name":"missile.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/missile.js"}
,
{"name":"physics.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/physics.js"}
,
{"name":"race.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/race.js"}
,
{"name":"skid-marks.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/skid-marks.js"}
,
{"name":"start-line.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/start-line.js"}
,
{"name":"tnt.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/tnt.js"}
,
{"name":"track.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/src/track.js"}
]}
,
{"name":"vite.config.js","type":"file","path":"snapshots/04-2130-items-and-effects/game/vite.config.js"}
]}
,
{"name":"gamepad-test","type":"dir","path":"snapshots/04-2130-items-and-effects/gamepad-test","children":[
{"name":"index.html","type":"file","path":"snapshots/04-2130-items-and-effects/gamepad-test/index.html"}
,
{"name":"main.js","type":"file","path":"snapshots/04-2130-items-and-effects/gamepad-test/main.js"}
]}
,
{"name":"kart-gen","type":"dir","path":"snapshots/04-2130-items-and-effects/kart-gen","children":[
{"name":"index.html","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/04-2130-items-and-effects/kart-gen/src","children":[
{"name":"main.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/main.ts"}
,
{"name":"objects","type":"dir","path":"snapshots/04-2130-items-and-effects/kart-gen/src/objects","children":[
{"name":"example-cart.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/objects/example-cart.ts"}
,
{"name":"firetruck.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/objects/firetruck.ts"}
,
{"name":"registry.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/objects/registry.ts"}
,
{"name":"types.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/objects/types.ts"}
,
{"name":"wonky-kart.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/objects/wonky-kart.ts"}
]}
,
{"name":"renderer.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/renderer.ts"}
,
{"name":"sprite-exporter.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/sprite-exporter.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/04-2130-items-and-effects/kart-gen/vite.config.ts"}
]}
,
{"name":"map-editor","type":"dir","path":"snapshots/04-2130-items-and-effects/map-editor","children":[
{"name":"index.html","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/04-2130-items-and-effects/map-editor/src","children":[
{"name":"editor.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/editor.ts"}
,
{"name":"main.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/main.ts"}
,
{"name":"preview3d.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/preview3d.ts"}
,
{"name":"save.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/save.ts"}
,
{"name":"state.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/state.ts"}
,
{"name":"tools.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/tools.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/04-2130-items-and-effects/map-editor/vite.config.ts"}
]}
,
{"name":"README.md","type":"file","path":"snapshots/04-2130-items-and-effects/README.md"}
]}
,
{"name":"05-2359-multiplayer","type":"dir","path":"snapshots/05-2359-multiplayer","children":[
{"name":"game","type":"dir","path":"snapshots/05-2359-multiplayer/game","children":[
{"name":"index.html","type":"file","path":"snapshots/05-2359-multiplayer/game/index.html"}
,
{"name":"src","type":"dir","path":"snapshots/05-2359-multiplayer/game/src","children":[
{"name":"boost-pad.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/boost-pad.js"}
,
{"name":"boost-visual.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/boost-visual.js"}
,
{"name":"bot-input.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/bot-input.js"}
,
{"name":"camera.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/camera.js"}
,
{"name":"debug.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/debug.js"}
,
{"name":"ground-decal.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/ground-decal.js"}
,
{"name":"hud.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/hud.js"}
,
{"name":"input.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/input.js"}
,
{"name":"item-boxes.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/item-boxes.js"}
,
{"name":"kart-collision.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/kart-collision.js"}
,
{"name":"kart.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/kart.js"}
,
{"name":"kart-visuals.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/kart-visuals.js"}
,
{"name":"lobby-ui.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/lobby-ui.js"}
,
{"name":"main.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/main.js"}
,
{"name":"map-loader.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/map-loader.js"}
,
{"name":"menu.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/menu.js"}
,
{"name":"missile.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/missile.js"}
,
{"name":"multiplayer-game.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/multiplayer-game.js"}
,
{"name":"net","type":"dir","path":"snapshots/05-2359-multiplayer/game/src/net","children":[
{"name":"connection.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/net/connection.js"}
,
{"name":"game-client.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/net/game-client.js"}
,
{"name":"interpolation.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/net/interpolation.js"}
,
{"name":"lobby-client.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/net/lobby-client.js"}
,
{"name":"prediction.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/net/prediction.js"}
]}
,
{"name":"physics.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/physics.js"}
,
{"name":"race.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/race.js"}
,
{"name":"skid-marks.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/skid-marks.js"}
,
{"name":"start-line.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/start-line.js"}
,
{"name":"tnt.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/tnt.js"}
,
{"name":"track.js","type":"file","path":"snapshots/05-2359-multiplayer/game/src/track.js"}
]}
,
{"name":"vite.config.js","type":"file","path":"snapshots/05-2359-multiplayer/game/vite.config.js"}
]}
,
{"name":"game_decals","type":"dir","path":"snapshots/05-2359-multiplayer/game_decals","children":[
{"name":"src","type":"dir","path":"snapshots/05-2359-multiplayer/game_decals/src","children":[
{"name":"decal-loader.js","type":"file","path":"snapshots/05-2359-multiplayer/game_decals/src/decal-loader.js"}
,
{"name":"quad-decal.js","type":"file","path":"snapshots/05-2359-multiplayer/game_decals/src/quad-decal.js"}
]}
]}
,
{"name":"gamepad-test","type":"dir","path":"snapshots/05-2359-multiplayer/gamepad-test","children":[
{"name":"index.html","type":"file","path":"snapshots/05-2359-multiplayer/gamepad-test/index.html"}
,
{"name":"main.js","type":"file","path":"snapshots/05-2359-multiplayer/gamepad-test/main.js"}
]}
,
{"name":"kart-gen","type":"dir","path":"snapshots/05-2359-multiplayer/kart-gen","children":[
{"name":"index.html","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/05-2359-multiplayer/kart-gen/src","children":[
{"name":"main.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/main.ts"}
,
{"name":"objects","type":"dir","path":"snapshots/05-2359-multiplayer/kart-gen/src/objects","children":[
{"name":"example-cart.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/objects/example-cart.ts"}
,
{"name":"firetruck.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/objects/firetruck.ts"}
,
{"name":"registry.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/objects/registry.ts"}
,
{"name":"types.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/objects/types.ts"}
,
{"name":"wonky-kart.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/objects/wonky-kart.ts"}
]}
,
{"name":"renderer.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/renderer.ts"}
,
{"name":"sprite-exporter.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/sprite-exporter.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/05-2359-multiplayer/kart-gen/vite.config.ts"}
]}
,
{"name":"map-editor","type":"dir","path":"snapshots/05-2359-multiplayer/map-editor","children":[
{"name":"index.html","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/index.html"}
,
{"name":"package.json","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/package.json"}
,
{"name":"src","type":"dir","path":"snapshots/05-2359-multiplayer/map-editor/src","children":[
{"name":"decals.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/decals.ts"}
,
{"name":"editor.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/editor.ts"}
,
{"name":"main.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/main.ts"}
,
{"name":"preview3d.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/preview3d.ts"}
,
{"name":"save.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/save.ts"}
,
{"name":"state.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/state.ts"}
,
{"name":"tools.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/tools.ts"}
,
{"name":"ui.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/src/ui.ts"}
]}
,
{"name":"tsconfig.json","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/tsconfig.json"}
,
{"name":"vite.config.ts","type":"file","path":"snapshots/05-2359-multiplayer/map-editor/vite.config.ts"}
]}
,
{"name":"README.md","type":"file","path":"snapshots/05-2359-multiplayer/README.md"}
,
{"name":"server","type":"dir","path":"snapshots/05-2359-multiplayer/server","children":[
{"name":"index.js","type":"file","path":"snapshots/05-2359-multiplayer/server/index.js"}
,
{"name":"lobby.js","type":"file","path":"snapshots/05-2359-multiplayer/server/lobby.js"}
,
{"name":"package.json","type":"file","path":"snapshots/05-2359-multiplayer/server/package.json"}
,
{"name":"room.js","type":"file","path":"snapshots/05-2359-multiplayer/server/room.js"}
,
{"name":"server-boost-pads.js","type":"file","path":"snapshots/05-2359-multiplayer/server/server-boost-pads.js"}
,
{"name":"server-items.js","type":"file","path":"snapshots/05-2359-multiplayer/server/server-items.js"}
,
{"name":"server-map-loader.js","type":"file","path":"snapshots/05-2359-multiplayer/server/server-map-loader.js"}
,
{"name":"server-missile.js","type":"file","path":"snapshots/05-2359-multiplayer/server/server-missile.js"}
,
{"name":"server-tnt.js","type":"file","path":"snapshots/05-2359-multiplayer/server/server-tnt.js"}
]}
]}
]}
,
{"name":"spritesheet.png","type":"file","path":"spritesheet.png"}
]}
;
